[tools]
claude = "latest"
java = "temurin-21"
lazygit = "latest"
lua-language-server = "latest"
neovim = "0.11.6"
node = "lts"
"npm:@fsouza/prettierd" = "latest"
"npm:@vtsls/language-server" = "latest"
"npm:tree-sitter-cli" = "latest"
ripgrep = "latest"
starship = "latest"
stylua = "latest"
yazi = "latest"
